version: "3"  

services: 
  backend-itau:  
    build: .  
    command: npm start 
    ports:
      - "${PORT}:${PORT}"  
    volumes:
      - .:/usr/app  
    env_file:
      - ./.env
    expose:
      - ${PORT}