config:
  target: "http://localhost:4000"
  
  phases:
    - duration: 60
      arrivalRate: 300
      name: Teste bruto - 300 req/s

    
  payload:
    - path: 'datas.csv'
      fields:
        - data 

scenarios: 
  - name: 'Adicionar transacao'
    weight: 15
    flow: 
      - post:
          url: '/Transacao'
          json:
            valor: 10
            dataHora: "{{ data }}"

  - name: 'Remover transacao'
    weight: 1
    flow:
      - delete: 
          url: '/Transacao'
        
  - name: 'Imprimir Estatisticas'
    weight: 4
    flow: 
      - get:
          url: '/Estatisticas'
          qs:
            tempo: 300
